"""empty message

Revision ID: 26c0636930b7
Revises: 0f5f83edf19e
Create Date: 2024-03-18 19:53:51.149788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c0636930b7'
down_revision = '0f5f83edf19e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sneaker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sneaker_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sneaker', schema=None) as batch_op:
        batch_op.drop_column('sneaker_name')

    # ### end Alembic commands ###
